import React, { FC, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { getRandom } from '../../axios/user';
import { useAppSelector } from '../../redux/hooks';
import { RootState } from '../../redux/store';


interface SecureProps { }

const Secure: FC<SecureProps> = () => {
  const [random, setRandom] = useState<string>();
  const token = useAppSelector((state: RootState) => state.auth.token);
  useEffect(() => {
    const fetchData = async () => {
      if (token) {
        const randomData = await getRandom(token);
        setRandom(randomData)
      }
    }
    fetchData();
  }, [token]);


  return <div data-testid="Secure">
    <div className='row'>
      <div className='col-12 col-md-6 offset-md-3'>
        <h2>Secure Page</h2>
        {random && <p className='bg-primary text-white'>Random code (Generated by server, requires valid login and JWT Token) <br /> {random}</p>}
        <Link to="/secure/users">User List</Link>

      </div>
    </div>
  </div>
};

export default Secure;
